version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build:
    machine: true
    environment:
      - IMAGE: deploy_machine
    steps:
      - checkout
      - run:
          name: Authenticate
          command: |
            make auth
      - run:
          name: Build
          command: |
            make build
workflows:
  version: 2
  build_container:
    jobs:
      - build:
          context: org-global
